name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10.16'
      - name: Install Dependencies
        run: yarn --frozen-lockfile
      - name: Build & Deploy
        run: yarn deploy
